#!/usr/bin/env node

var s3touch = require('./index.js');

if (process.argv.length < 3) console.log(s3touch.usage()) && process.exit(1);

var s3paths = process.argv.slice(2);
var cache = {};

function run(err, data) {
    if (err) {
        console.warn(err.toString());
        process.exit(1);
    }
    if (data) {
        console.log('ok - ' + s3paths[0]);
        s3paths.shift();
    }
    if (s3paths.length) {
        s3touch.touch(s3paths[0], cache, run);
    }
}

run();
